name: CI/CD Docker Deployment

on:
  push:
    branches:
      - main  # Exécute le pipeline à chaque push sur la branche principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construction de l'image Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mon_serveur:latest .

      - name: Push de l'image vers DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mon_serveur:latest
